/**
 * IDE themes — each defines CSS variable values applied to :root
 * and the Monaco editor theme name.
 */

export const THEMES = {
  'dark': {
    name: 'Dark (Default)',
    monacoTheme: 'vs-dark',
    vars: {
      '--bg-app':         '#1e1e1e',
      '--bg-titlebar':    '#1f1f1f',
      '--bg-activitybar': '#181818',
      '--bg-sidepanel':   '#1e1e1e',
      '--bg-editor':      '#1e1e1e',
      '--bg-bottompanel': '#1e1e1e',
      '--bg-tab-active':  '#1e1e1e',
      '--bg-tab-inactive':'#2d2d2d',
      '--bg-panel':       '#252526',
      '--bg-input':       '#3c3c3c',
      '--bg-hover':       '#2a2d2e',
      '--bg-selected':    '#094771',
      '--border':         '#333333',
      '--border-light':   '#444444',
      '--text-primary':   '#cccccc',
      '--text-secondary': '#858585',
      '--text-muted':     '#555555',
      '--text-bright':    '#d4d4d4',
      '--accent':         '#007acc',
      '--accent-hover':   '#0098ff',
      '--statusbar-bg':   '#007acc',
      '--statusbar-text': '#ffffff',
      '--scrollbar':      '#424242',
    },
  },

  'light': {
    name: 'Light',
    monacoTheme: 'vs',
    vars: {
      '--bg-app':         '#f3f3f3',
      '--bg-titlebar':    '#dddddd',
      '--bg-activitybar': '#2c2c2c',
      '--bg-sidepanel':   '#f3f3f3',
      '--bg-editor':      '#ffffff',
      '--bg-bottompanel': '#f3f3f3',
      '--bg-tab-active':  '#ffffff',
      '--bg-tab-inactive':'#ececec',
      '--bg-panel':       '#f8f8f8',
      '--bg-input':       '#ffffff',
      '--bg-hover':       '#e8e8e8',
      '--bg-selected':    '#cce5ff',
      '--border':         '#d4d4d4',
      '--border-light':   '#cccccc',
      '--text-primary':   '#333333',
      '--text-secondary': '#6e6e6e',
      '--text-muted':     '#999999',
      '--text-bright':    '#1a1a1a',
      '--accent':         '#007acc',
      '--accent-hover':   '#005fa3',
      '--statusbar-bg':   '#007acc',
      '--statusbar-text': '#ffffff',
      '--scrollbar':      '#c1c1c1',
    },
  },

  'dracula': {
    name: 'Dracula',
    monacoTheme: 'vs-dark',
    vars: {
      '--bg-app':         '#282a36',
      '--bg-titlebar':    '#21222c',
      '--bg-activitybar': '#191a21',
      '--bg-sidepanel':   '#282a36',
      '--bg-editor':      '#282a36',
      '--bg-bottompanel': '#282a36',
      '--bg-tab-active':  '#282a36',
      '--bg-tab-inactive':'#21222c',
      '--bg-panel':       '#21222c',
      '--bg-input':       '#44475a',
      '--bg-hover':       '#44475a',
      '--bg-selected':    '#44475a',
      '--border':         '#44475a',
      '--border-light':   '#6272a4',
      '--text-primary':   '#f8f8f2',
      '--text-secondary': '#6272a4',
      '--text-muted':     '#44475a',
      '--text-bright':    '#ffffff',
      '--accent':         '#bd93f9',
      '--accent-hover':   '#ff79c6',
      '--statusbar-bg':   '#bd93f9',
      '--statusbar-text': '#282a36',
      '--scrollbar':      '#44475a',
    },
  },

  'nord': {
    name: 'Nord',
    monacoTheme: 'vs-dark',
    vars: {
      '--bg-app':         '#2e3440',
      '--bg-titlebar':    '#2e3440',
      '--bg-activitybar': '#2e3440',
      '--bg-sidepanel':   '#2e3440',
      '--bg-editor':      '#2e3440',
      '--bg-bottompanel': '#2e3440',
      '--bg-tab-active':  '#3b4252',
      '--bg-tab-inactive':'#2e3440',
      '--bg-panel':       '#3b4252',
      '--bg-input':       '#3b4252',
      '--bg-hover':       '#434c5e',
      '--bg-selected':    '#4c566a',
      '--border':         '#3b4252',
      '--border-light':   '#434c5e',
      '--text-primary':   '#d8dee9',
      '--text-secondary': '#81a1c1',
      '--text-muted':     '#4c566a',
      '--text-bright':    '#eceff4',
      '--accent':         '#88c0d0',
      '--accent-hover':   '#81a1c1',
      '--statusbar-bg':   '#5e81ac',
      '--statusbar-text': '#eceff4',
      '--scrollbar':      '#4c566a',
    },
  },

  'monokai': {
    name: 'Monokai',
    monacoTheme: 'vs-dark',
    vars: {
      '--bg-app':         '#272822',
      '--bg-titlebar':    '#1e1f1c',
      '--bg-activitybar': '#1e1f1c',
      '--bg-sidepanel':   '#272822',
      '--bg-editor':      '#272822',
      '--bg-bottompanel': '#272822',
      '--bg-tab-active':  '#272822',
      '--bg-tab-inactive':'#1e1f1c',
      '--bg-panel':       '#1e1f1c',
      '--bg-input':       '#3e3d32',
      '--bg-hover':       '#3e3d32',
      '--bg-selected':    '#49483e',
      '--border':         '#3e3d32',
      '--border-light':   '#75715e',
      '--text-primary':   '#f8f8f2',
      '--text-secondary': '#75715e',
      '--text-muted':     '#49483e',
      '--text-bright':    '#ffffff',
      '--accent':         '#a6e22e',
      '--accent-hover':   '#f92672',
      '--statusbar-bg':   '#75715e',
      '--statusbar-text': '#f8f8f2',
      '--scrollbar':      '#49483e',
    },
  },

  'solarized-dark': {
    name: 'Solarized Dark',
    monacoTheme: 'vs-dark',
    vars: {
      '--bg-app':         '#002b36',
      '--bg-titlebar':    '#073642',
      '--bg-activitybar': '#002b36',
      '--bg-sidepanel':   '#002b36',
      '--bg-editor':      '#002b36',
      '--bg-bottompanel': '#002b36',
      '--bg-tab-active':  '#073642',
      '--bg-tab-inactive':'#002b36',
      '--bg-panel':       '#073642',
      '--bg-input':       '#073642',
      '--bg-hover':       '#073642',
      '--bg-selected':    '#094771',
      '--border':         '#073642',
      '--border-light':   '#586e75',
      '--text-primary':   '#839496',
      '--text-secondary': '#586e75',
      '--text-muted':     '#073642',
      '--text-bright':    '#93a1a1',
      '--accent':         '#268bd2',
      '--accent-hover':   '#2aa198',
      '--statusbar-bg':   '#268bd2',
      '--statusbar-text': '#fdf6e3',
      '--scrollbar':      '#073642',
    },
  },

  'github-dark': {
    name: 'GitHub Dark',
    monacoTheme: 'vs-dark',
    vars: {
      '--bg-app':         '#0d1117',
      '--bg-titlebar':    '#161b22',
      '--bg-activitybar': '#010409',
      '--bg-sidepanel':   '#0d1117',
      '--bg-editor':      '#0d1117',
      '--bg-bottompanel': '#0d1117',
      '--bg-tab-active':  '#0d1117',
      '--bg-tab-inactive':'#161b22',
      '--bg-panel':       '#161b22',
      '--bg-input':       '#21262d',
      '--bg-hover':       '#21262d',
      '--bg-selected':    '#1f6feb',
      '--border':         '#30363d',
      '--border-light':   '#484f58',
      '--text-primary':   '#c9d1d9',
      '--text-secondary': '#8b949e',
      '--text-muted':     '#484f58',
      '--text-bright':    '#f0f6fc',
      '--accent':         '#58a6ff',
      '--accent-hover':   '#79c0ff',
      '--statusbar-bg':   '#1f6feb',
      '--statusbar-text': '#ffffff',
      '--scrollbar':      '#30363d',
    },
  },

  'tokyo-night': {
    name: 'Tokyo Night',
    monacoTheme: 'vs-dark',
    vars: {
      '--bg-app':         '#1a1b26',
      '--bg-titlebar':    '#16161e',
      '--bg-activitybar': '#16161e',
      '--bg-sidepanel':   '#1a1b26',
      '--bg-editor':      '#1a1b26',
      '--bg-bottompanel': '#1a1b26',
      '--bg-tab-active':  '#1a1b26',
      '--bg-tab-inactive':'#16161e',
      '--bg-panel':       '#16161e',
      '--bg-input':       '#1f2335',
      '--bg-hover':       '#1f2335',
      '--bg-selected':    '#283457',
      '--border':         '#1f2335',
      '--border-light':   '#3b4261',
      '--text-primary':   '#a9b1d6',
      '--text-secondary': '#565f89',
      '--text-muted':     '#3b4261',
      '--text-bright':    '#c0caf5',
      '--accent':         '#7aa2f7',
      '--accent-hover':   '#bb9af7',
      '--statusbar-bg':   '#7aa2f7',
      '--statusbar-text': '#1a1b26',
      '--scrollbar':      '#1f2335',
    },
  },
}

export const THEME_KEYS = Object.keys(THEMES)
export const DEFAULT_THEME = 'dark'

/**
 * Apply a theme by setting CSS variables on :root
 */
export function applyTheme(themeKey) {
  const theme = THEMES[themeKey] || THEMES['dark']
  const root = document.documentElement
  Object.entries(theme.vars).forEach(([key, val]) => {
    root.style.setProperty(key, val)
  })
  root.setAttribute('data-theme', themeKey)
  return theme
}
